"""add_documentos_table

Revision ID: e9a8ea64a0f8
Revises: 6ac4cd42f331
Create Date: 2026-09-18 19:41:23.621433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a8ea64a0f8'
down_revision: Union[str, None] = '6ac4cd42f331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos',
    sa.Column('cod_socio', sa.String(length=20), nullable=False),
    sa.Column('tipo_documento', sa.String(length=30), nullable=False),
    sa.Column('nro_factura', sa.String(length=50), nullable=True),
    sa.Column('nro_facip', sa.String(length=50), nullable=True),
    sa.Column('cod_autorizacion', sa.String(length=100), nullable=True),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('monto_bs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('s3_key', sa.String(length=255), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('estado_pago', sa.String(length=20), nullable=False),
    sa.Column('suministro_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['suministro_id'], ['suministros.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_socio', 'tipo_documento', 'periodo', name='uq_socio_tipo_periodo')
    )
    op.create_index(op.f('ix_documentos_cod_socio'), 'documentos', ['cod_socio'], unique=False)
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_nro_factura'), 'documentos', ['nro_factura'], unique=False)
    op.create_index(op.f('ix_documentos_suministro_id'), 'documentos', ['suministro_id'], unique=False)
    op.create_index(op.f('ix_documentos_tipo_documento'), 'documentos', ['tipo_documento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_tipo_documento'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_suministro_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_nro_factura'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_cod_socio'), table_name='documentos')
    op.drop_table('documentos')
    # ### end Alembic commands ###
