"""crear_tablas_identidad_y_auth

Revision ID: 6ac4cd42f331
Revises: 
Create Date: 2026-09-17 14:09:21.009956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac4cd42f331'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otps',
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('proposito', sa.String(length=30), nullable=False),
    sa.Column('fue_verificado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_index(op.f('ix_otps_telefono'), 'otps', ['telefono'], unique=False)
    op.create_table('usuarios',
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_telefono'), 'usuarios', ['telefono'], unique=True)
    op.create_table('dispositivos',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('modelo_dispositivo', sa.String(length=100), nullable=True),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispositivos_device_id'), 'dispositivos', ['device_id'], unique=False)
    op.create_index(op.f('ix_dispositivos_id'), 'dispositivos', ['id'], unique=False)
    op.create_index(op.f('ix_dispositivos_usuario_id'), 'dispositivos', ['usuario_id'], unique=False)
    op.create_table('suministros',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('cod_socio', sa.String(length=20), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('es_suministro_principal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'cod_socio', name='uq_usuario_cod_socio')
    )
    op.create_index(op.f('ix_suministros_cod_socio'), 'suministros', ['cod_socio'], unique=False)
    op.create_index(op.f('ix_suministros_id'), 'suministros', ['id'], unique=False)
    op.create_index(op.f('ix_suministros_usuario_id'), 'suministros', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suministros_usuario_id'), table_name='suministros')
    op.drop_index(op.f('ix_suministros_id'), table_name='suministros')
    op.drop_index(op.f('ix_suministros_cod_socio'), table_name='suministros')
    op.drop_table('suministros')
    op.drop_index(op.f('ix_dispositivos_usuario_id'), table_name='dispositivos')
    op.drop_index(op.f('ix_dispositivos_id'), table_name='dispositivos')
    op.drop_index(op.f('ix_dispositivos_device_id'), table_name='dispositivos')
    op.drop_table('dispositivos')
    op.drop_index(op.f('ix_usuarios_telefono'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_otps_telefono'), table_name='otps')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_table('otps')
    # ### end Alembic commands ###
