"""add_auditoria_pagos_redireccion_table

Revision ID: 204a5f9f8fef
Revises: e9a8ea64a0f8
Create Date: 2026-09-22 14:47:39.754494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204a5f9f8fef'
down_revision: Union[str, None] = 'e9a8ea64a0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_pagos_redireccion',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('cod_socio', sa.String(length=20), nullable=False),
    sa.Column('canal_id', sa.String(length=30), nullable=False),
    sa.Column('monto_deuda_bs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ip_origen', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_pagos_redireccion_canal_id'), 'auditoria_pagos_redireccion', ['canal_id'], unique=False)
    op.create_index(op.f('ix_auditoria_pagos_redireccion_cod_socio'), 'auditoria_pagos_redireccion', ['cod_socio'], unique=False)
    op.create_index(op.f('ix_auditoria_pagos_redireccion_id'), 'auditoria_pagos_redireccion', ['id'], unique=False)
    op.create_index(op.f('ix_auditoria_pagos_redireccion_usuario_id'), 'auditoria_pagos_redireccion', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditoria_pagos_redireccion_usuario_id'), table_name='auditoria_pagos_redireccion')
    op.drop_index(op.f('ix_auditoria_pagos_redireccion_id'), table_name='auditoria_pagos_redireccion')
    op.drop_index(op.f('ix_auditoria_pagos_redireccion_cod_socio'), table_name='auditoria_pagos_redireccion')
    op.drop_index(op.f('ix_auditoria_pagos_redireccion_canal_id'), table_name='auditoria_pagos_redireccion')
    op.drop_table('auditoria_pagos_redireccion')
    # ### end Alembic commands ###
